<?php

namespace Database\Seeders;

use App\Models\AutomaticProcess;
use App\Models\Tenant;
use App\Services\Automation\AutomaticProcessScheduler;
use Illuminate\Database\Seeder;

class AutomaticProcessSeeder extends Seeder
{
    public function run(): void
    {
        $tenantId = (int) (Tenant::query()->value('id') ?? 1);
        $scheduler = app(AutomaticProcessScheduler::class);

        $defaults = [
            [
                'slug' => 'fup-usage-alerts',
                'name' => 'FUP data usage alerts',
                'description' => 'Warn subscribers before bill when nearing daily data quota.',
                'artisan_command' => 'isp:send-fup-usage-alerts',
                'command_options' => [],
                'execute_at' => '03:05',
                'interval' => 'daily',
                'when_config_key' => 'billing.fup_alerts.enabled',
                'sort_order' => 8,
            ],
            [
                'slug' => 'apply-scheduled-package-changes',
                'name' => 'Apply scheduled package changes',
                'description' => 'Downgrades/changes queued from customer portal for next billing cycle.',
                'artisan_command' => 'isp:apply-scheduled-package-changes',
                'command_options' => [],
                'execute_at' => '03:12',
                'interval' => 'daily',
                'when_config_key' => 'billing.downgrade_next_cycle',
                'sort_order' => 9,
            ],
            [
                'slug' => 'generate-bills-daily',
                'name' => 'Generate bills (daily cycle)',
                'artisan_command' => 'isp:generate-bills',
                'command_options' => ['--cycle' => 'daily'],
                'execute_at' => '03:10',
                'interval' => 'daily',
                'sort_order' => 10,
            ],
            [
                'slug' => 'generate-bills-monthly',
                'name' => 'Generate bills (monthly)',
                'description' => 'Runs daily at 03:15; creates invoices when subscriber bill day matches (default: 1st of month).',
                'artisan_command' => 'isp:generate-bills',
                'command_options' => [],
                'execute_at' => '03:15',
                'interval' => 'daily',
                'sort_order' => 20,
            ],
            [
                'slug' => 'generate-bills-hourly',
                'name' => 'Generate bills (hourly cycle)',
                'artisan_command' => 'isp:generate-bills',
                'command_options' => ['--cycle' => 'hourly'],
                'execute_at' => '00:00',
                'interval' => 'hourly',
                'sort_order' => 30,
            ],
            [
                'slug' => 'apply-late-fees',
                'name' => 'Apply late fees',
                'artisan_command' => 'isp:apply-late-fees',
                'command_options' => [],
                'execute_at' => '04:00',
                'interval' => 'daily',
                'sort_order' => 40,
            ],
            [
                'slug' => 'invoice-due-reminders',
                'name' => 'Smart dunning reminders',
                'description' => 'Due soon, due today, and overdue SMS/email ladder.',
                'artisan_command' => 'isp:send-invoice-due-reminders',
                'command_options' => [],
                'execute_at' => '09:00',
                'interval' => 'daily',
                'sort_order' => 50,
            ],
            [
                'slug' => 'piprapay-sync-pending',
                'name' => 'PipraPay pending payment sync',
                'description' => 'After manual approval in PipraPay merchant panel, poll verify API and record payments on ISP.',
                'artisan_command' => 'piprapay:sync-pending',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_five_minutes',
                'when_config_key' => 'piprapay.enabled',
                'sort_order' => 55,
            ],
            [
                'slug' => 'prepaid-wallet-settle',
                'name' => 'Prepaid wallet auto-settle',
                'description' => 'Apply wallet to prepaid bills and extend service expiry.',
                'artisan_command' => 'isp:prepaid-wallet-settle',
                'command_options' => [],
                'execute_at' => '03:25',
                'interval' => 'daily',
                'when_config_key' => 'automation.prepaid_wallet_settle.enabled',
                'sort_order' => 52,
            ],
            [
                'slug' => 'evaluate-service-expiry',
                'name' => 'Evaluate service expiry',
                'artisan_command' => 'isp:evaluate-service-expiry',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_fifteen_minutes',
                'when_config_key' => 'network.service_expiry_enforced',
                'sort_order' => 60,
            ],
            [
                'slug' => 'network-evaluate-access',
                'name' => 'Auto suspend / reconnect (network access)',
                'description' => 'Enables paid subscribers and suspends overdue accounts on MikroTik/GPON.',
                'artisan_command' => 'isp:network-evaluate-access',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_fifteen_minutes',
                'when_config_key' => 'network.auto_suspend_enabled',
                'without_overlapping_minutes' => 12,
                'sort_order' => 68,
            ],
            [
                'slug' => 'disable-unpaid-customers',
                'name' => 'Disable unpaid customers (daily sweep)',
                'description' => 'Extra daily pass for overdue suspension rules.',
                'artisan_command' => 'isp:network-evaluate-access',
                'command_options' => [],
                'execute_at' => '11:00',
                'interval' => 'daily',
                'when_config_key' => 'network.auto_suspend_enabled',
                'sort_order' => 70,
            ],
            [
                'slug' => 'mikrotik-session-integrity',
                'name' => 'MikroTik session integrity scan',
                'description' => 'Detect multi-router logins, wrong-router sessions, and overdue subscribers still online.',
                'artisan_command' => 'isp:mikrotik-session-integrity',
                'command_options' => [],
                'execute_at' => '06:30',
                'interval' => 'hourly',
                'when_config_key' => 'network.session_integrity_enabled',
                'sort_order' => 72,
            ],
            [
                'slug' => 'check-reseller-negative-balance',
                'name' => 'Check negative balance of MAC resellers',
                'artisan_command' => 'isp:check-reseller-negative-balance',
                'command_options' => [],
                'execute_at' => '07:00',
                'interval' => 'daily',
                'when_config_key' => 'automation.reseller_negative_balance.enabled',
                'sort_order' => 75,
            ],
            [
                'slug' => 'postpaid-pop-fund-credit',
                'name' => 'Fund credit & disable of postpaid POPs',
                'description' => 'Applies wallet to postpaid bills, then suspends still-unpaid subscribers.',
                'artisan_command' => 'isp:postpaid-pop-fund-credit',
                'command_options' => [],
                'execute_at' => '00:05',
                'interval' => 'daily',
                'when_config_key' => 'automation.postpaid_fund_credit.enabled',
                'sort_order' => 77,
            ],
            [
                'slug' => 'sync-customers-from-servers',
                'name' => 'Sync all customer by servers',
                'artisan_command' => 'isp:sync-customers-from-servers',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'hourly',
                'when_config_key' => 'subscriber.auto_import_secrets_enabled',
                'sort_order' => 78,
            ],
            [
                'slug' => 'mikrotik-poll-status',
                'name' => 'MikroTik PPP online status poll',
                'artisan_command' => 'isp:mikrotik-poll-status',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_two_minutes',
                'without_overlapping_minutes' => 3,
                'when_config_key' => 'mikrotik.poll_enabled',
                'sort_order' => 80,
            ],
            [
                'slug' => 'mikrotik-fetch-details',
                'name' => 'MikroTik router health & details sync',
                'artisan_command' => 'isp:mikrotik-fetch-details',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_fifteen_minutes',
                'without_overlapping_minutes' => 10,
                'when_config_key' => 'mikrotik.fetch_details_poll_enabled',
                'sort_order' => 82,
            ],
            [
                'slug' => 'import-mikrotik-secrets',
                'name' => 'Import MikroTik PPP secrets (hourly)',
                'artisan_command' => 'isp:import-mikrotik-secrets',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'hourly',
                'when_config_key' => 'subscriber.auto_import_secrets_enabled',
                'enabled' => false,
                'sort_order' => 90,
            ],
            [
                'slug' => 'collect-bandwidth',
                'name' => 'Collect bandwidth usage',
                'artisan_command' => 'isp:collect-bandwidth',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_five_minutes',
                'when_config_key' => 'bandwidth.collection_enabled',
                'without_overlapping_minutes' => 8,
                'sort_order' => 100,
            ],
            [
                'slug' => 'poll-olt-intelligence',
                'name' => 'OLT SNMP intelligence poll',
                'artisan_command' => 'isp:poll-olt-intelligence',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_ten_minutes',
                'when_config_key' => 'network.olt_snmp_poll_enabled',
                'sort_order' => 110,
            ],
            [
                'slug' => 'ispdigital-onu-sync',
                'name' => 'ISP Digital ONU sync (OLT → link → dBm)',
                'description' => 'BDCOM SNMP inventory, PPP login match, optical power — same flow as ISP Digital panel.',
                'artisan_command' => 'isp:ispdigital-onu-sync',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_three_minutes',
                'when_config_key' => 'optical.isp_digital_auto_sync',
                'without_overlapping_minutes' => 5,
                'sort_order' => 118,
            ],
            [
                'slug' => 'sync-bdcom-epon-onus',
                'name' => 'Sync BDCOM EPON ONUs (GPON inventory)',
                'artisan_command' => 'isp:sync-bdcom-epon-onus',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_three_minutes',
                'when_config_key' => 'optical.enabled',
                'without_overlapping_minutes' => 5,
                'sort_order' => 120,
            ],
            [
                'slug' => 'collect-onu-signals',
                'name' => 'ONU signal monitoring (dB / LOS)',
                'artisan_command' => 'isp:collect-onu-signals',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_five_minutes',
                'when_config_key' => 'optical.enabled',
                'without_overlapping_minutes' => 8,
                'sort_order' => 130,
            ],
            [
                'slug' => 'auto-link-customer-onus',
                'name' => 'Auto-link customer ONUs by MAC',
                'artisan_command' => 'isp:auto-link-customer-onus',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'hourly',
                'when_config_key' => 'optical.auto_provision_customer_onu',
                'sort_order' => 135,
            ],
            [
                'slug' => 'ensure-customer-onus',
                'name' => 'Ensure customer ONUs provisioned',
                'artisan_command' => 'isp:ensure-customer-onus',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_fifteen_minutes',
                'when_config_key' => 'optical.auto_provision_customer_onu',
                'sort_order' => 140,
            ],
            [
                'slug' => 'smart-link-customer-onus',
                'name' => 'Smart-link customer ONUs',
                'artisan_command' => 'isp:smart-link-customer-onus',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_fifteen_minutes',
                'when_config_key' => 'optical.auto_provision_customer_onu',
                'sort_order' => 150,
            ],
            [
                'slug' => 'process-netflow-inbox',
                'name' => 'Process NetFlow inbox',
                'artisan_command' => 'isp:process-netflow-inbox',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_five_minutes',
                'when_config_key' => 'netflow.enabled',
                'sort_order' => 160,
            ],
            [
                'slug' => 'sync-onu-status-from-meta',
                'name' => 'Sync ONU status from device meta',
                'artisan_command' => 'isp:sync-onu-status-from-meta',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_fifteen_minutes',
                'when_config_key' => 'olt_vendors.meta_sync_enabled',
                'sort_order' => 170,
            ],
            [
                'slug' => 'support-check-sla',
                'name' => 'Support SLA check',
                'artisan_command' => 'isp:support-check-sla',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_thirty_minutes',
                'sort_order' => 180,
            ],
            [
                'slug' => 'sales-lead-follow-ups',
                'name' => 'Sales lead follow-ups',
                'artisan_command' => 'isp:sales-lead-follow-ups',
                'command_options' => [],
                'execute_at' => '09:30',
                'interval' => 'daily',
                'sort_order' => 190,
            ],
            [
                'slug' => 'platform-backup',
                'name' => 'Platform backup (database + files)',
                'description' => 'ZIP archive to storage/app/backups for download or disaster recovery.',
                'artisan_command' => 'isp:platform-backup',
                'command_options' => [],
                'execute_at' => '02:00',
                'interval' => 'daily',
                'sort_order' => 205,
            ],
            [
                'slug' => 'check-sms-health',
                'name' => 'SMS / notification gateway health',
                'description' => 'Verifies SMS provider connectivity and quota.',
                'artisan_command' => 'isp:check-sms-health',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_five_minutes',
                'sort_order' => 195,
            ],
            [
                'slug' => 'broadcast-dashboard-metrics',
                'name' => 'Broadcast live dashboard metrics',
                'artisan_command' => 'isp:broadcast-dashboard-metrics',
                'command_options' => [],
                'execute_at' => '00:00',
                'interval' => 'every_minute',
                'when_config_key' => null,
                'enabled' => in_array(config('broadcasting.default'), ['reverb', 'pusher'], true),
                'sort_order' => 200,
            ],
        ];

        foreach ($defaults as $row) {
            $enabled = (bool) ($row['enabled'] ?? true);
            unset($row['enabled']);

            $process = AutomaticProcess::query()->withoutGlobalScopes()->updateOrCreate(
                ['slug' => $row['slug']],
                array_merge($row, ['tenant_id' => $tenantId, 'enabled' => $enabled]),
            );

            if ($process->next_run_at === null) {
                $process->forceFill([
                    'next_run_at' => $scheduler->computeNextRunAt($process),
                ])->save();
            }
        }
    }
}
