name: mfs_verify
description: RCL SMS — Radiant ISP bKash/Nagad payment SMS auto-verify (device key).
publish_to: 'none'
version: 1.0.12+13

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.5
  telephony: ^0.2.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.1.2
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo.png
